language: python
sudo: required
python:
    - "2.6"
    - "2.7"
env: PGVERSION=9.1
dist: trusty
cache: pip
before_install:
    - chmod +x ./bin/travis-build.bash
    - chmod +x ./bin/travis-run.sh
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script:
    - sh bin/travis-run.sh
    - pycodestyle --count ./ckanext/saasportal_quote
after_success:
    - coveralls
